eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

spring:
  cloud:
    gateway:
      routes:
        - id: reserva-service
          uri: lb://RESERVA-SERVICE
          predicates:
            - Path=/api/v1/reservas,/api/v1/reservas/**
          filters:
            - name: CircuitBreaker
              args:
                name: reservaServiceGateway

        - id: usuario-service
          uri: lb://USUARIO-SERVICE
          predicates:
            - Path=/api/v1/usuarios,/api/v1/usuarios/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth,/api/v1/auth/**

management:
  tracing:
    sampling:
      probability: 1.0
  health:
      circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,refresh
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      productServiceGateway:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

      inventoryServiceGateway:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

      orderServiceGateway:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      productServiceGateway:
        maxAttempts: 5
        waitDuration: 10s

      inventoryServiceGateway:
        maxAttempts: 5
        waitDuration: 10s

      orderServiceGateway:
        maxAttempts: 5
        waitDuration: 10s
